### ISSUE TITLE
Introduce an Analyser phase

### ISSUE THREAD

**Issue by 54k1** [tuqqu/oxide-lang#8]
Taking advantage of the strongly typed nature of oxide, I propose the following:

1. Type checking phase: Invalid operations on expressions such as `-"asdf"`, `!12` are being checked at runtime, when they can be checked statically because we already know the types and their operations. This would involve writing a static type checker.
I suspect, however, that this has an issue due to the `any` type. The current behavior, lets a variable with the type `any` to take on values of other types without an explicit cast. Due to this, it would be hard to reason about operations on such a variable.
Therefore, we can't really get away with runtime checks due to `any`, unless of course, we change the way it behaves.

I would prefer an explicit cast when applying operators to variables of the type `any`. For instance,
```Rust
let x: any;
x = 12;
let y = (x as int) + 12;
```

We can introduce a lot more checks before the interpreter is run, leading to reporting more errors before the interpreter is run (at runtime), and also better performance(by getting away with unnecessary checks):
- Accessing invalid properties of a struct instance.
```rust
struct Person {
    pub name: String
}
let p: Person = Person::new();
println(p.age);
```
If `p` were of the type `any`, it would be very difficult and probably inefficient(in the worst case) to reason about the invalid property access.
- Same as the above with enum values.
- Matching argument types of a function call to its declaration (signature).

2. Apart from type checking, we can perform some basic analyses for things such as:
- Arity match check for function calls.
- Prevent re-declarations of struct/enums.
```rust
fn f() {
    fn g() {}
    enum E {}
}
f();
f();
```
In this case, any declaration inside a block is re-declared each time the block is run. The analyzer can possibly prune such declarations and hoist it at the top level.

@tuqqu please let me know what you think about these. Also, please feel free to correct me wherever necessary.
Is this in line with the vision you have for oxide?

**Comment by tuqqu** [comment]
I overall share your vision and agree that static analysis would be a great improvement to the language on the whole.

However creating such a tool would be quite an undertaking, as it introduces a whole new phase for the parsed AST.

This raises an issue that performing static analysis every time could slow the whole process, because analysing code statically is an interpretation to some degree that will affect the performance. Basically what we would be doing is interpreting the code twice: first we would go through the AST seeking errors and then interpreting as usual (on success). 

I think that due to the interpreted nature of the language we could benefit from borrowing the similar approaches other big languages use (like JavaScript/PHP/Python/Ruby). Correct me if I'm wrong, but they all have static analysis tools that are run optionally (e.g. JSLint, Psalm), either on deploy or manually to ensure you wrote a correct program.

This optional built-in static analysis tool could be called for instance like
```
oxide --lint script.ox
```
Probably the tool is best to be placed in a separate crate within the project. I am not really experienced in multi-crate Rust projects, but for reference [serde](https://github.com/serde-rs/serde) is doing something similar.

As for the ideas themselves:
* I like the idea of having to explicitly cast variable of type `any` before using it. Once we have type casting through `as` this is definitely what should be implemented. This `any` type is something I have not decided on to be honest. It is a bit quirky, yet _sometimes_ handy to have in a dynamic language. There is a chance we drop it altogether though. A big one :) 
* Catching the invalid enum value or struct property is a `+` from me
* Function signature validation and arity `+` as well

I am not sure what you mean by
> The analyzer can possibly prune such declarations and hoist it at the top level.

A `enum/struct/const/fn` declaration inside a function is not visible from the outside scope (and it is good), so hoisting them would not be correct. Maybe I am misunderstanding what you mean, but the optimisation here would be interpreting those declarations once and caching them somewhere. The next time this function gets called we can just use the cached declarations. 

But inner declarations are not really a common thing, are they? They are syntactically valid, but... a bit useless. Even in Rust I do not see people using them much. Is there much point in implementing the caching system for such a rare case? Maybe in the future.

**Comment by 54k1** [comment]
> This raises an issue that performing static analysis every time could slow the whole process, because analysing code statically is an interpretation to some degree that will affect the performance. Basically what we would be doing is interpreting the code twice: first we would go through the AST seeking errors and then interpreting as usual (on success).

Currently, the pipeline of the program is as follows:
**Source Code** -> [Lexical Analyser] -> **tokens** -> [Parser] -> **Syntax Tree** -> [Interpreter] -> Result

- I'm suggesting to operate on the syntax tree, and then pass the altered syntax tree to the interpreter.
- We would be sacrificing some performance due to this analysis. However, the runtime can be much faster because it would become devoid of unnecessary checks (for types and their operations, and so on). It's something like: the compilation takes a bit longer, but it runs much faster.
- For starters, we can have the optional linter like you suggest. Once it is mature, we can integrate it with the pipeline before the Interpreter stage.

> Correct me if I'm wrong, but they all have static analysis tools that are run optionally (e.g. JSLint, Psalm), either on deploy or manually to ensure you wrote a correct program.

AFAIK, due to their dynamic types, only a limited amount of static analysis can be performed. Due to this, we face a lot of unforeseen errors at runtime (which might have been caught at compile time, if it were a statically typed language)
`python3` has optional type annotations which many linters use. But those are not enforced at runtime. `JavaScript` has other tricks up its sleeves. It performs an optimization phase for "hot" code at runtime. ([Interesting blog post](https://mathiasbynens.be/notes/prototypes))

For oxide, I suggested static analysis because it is statically typed, unlike `JavaScript` or `python`.

>  the optimisation here would be interpreting those declarations once and caching them somewhere.

Absolutely! Like you said however, its not a very common practice and we can have it on low priority.

> However creating such a tool would be quite an undertaking, as it introduces a whole new phase for the parsed AST.

Yes, this is a mini project in itself. But it should be really interesting to work on IMO.

By no means, this is an exhaustive list of analyses we can work on. I'm sure a lot more can be added. We can add them to a list and assign priorities to each of them and tackle them one at a time. :)

Let me know if this works with you.

**Comment by tuqqu** [comment]
To be honest, I have to say that in the near future I envision myself mostly involved in the new features development (e.g. I am currently working on `trait`s). Here is an approximate list of necessary improvements as I see it for now:
* `trait` support
* `mod`ules support
* multifile support (in pair with modules)
* type casting (with `as`)

I also would like to see in the language:
* generics support
* `type`s support with intersection types (idea borrowed from TypeScript)
* enum satellite data support (not yet sure how it is gonna look tbh)
* primitive types boxing/unboxing (basically methods on numbers/str/bool).
* tuples (this is gonna be a hard one to implement I think)

This is I definitely support and agree with:

> For starters, we can have the optional linter like you suggest. Once it is mature, we can integrate it with the pipeline before the Interpreter stage.

As for this one: 

> Due to this, we face a lot of unforeseen errors at runtime (which might have been caught at compile time, if it were a statically typed language)

I am a bit sceptical static analysis will help to speed up the runtime significantly. I am glad to be mistaken tho.

Don't get me wrong, I am very much interested in your proposition and support it, I am just a bit unsure it is easily achievable.  I am also not sure if speed is the concern right now. Speed is always a good thing however.

If you are interested in the development of the static analysis tool, you have the green light for sure, either you choose to integrate it directly within this project (through a separate crate) or first develop as a standalone tool in its own repository to experiment with.
This is a great opportunity to dive into such a thing and I am sure it is an interesting initiative. Let me know what you decide to get involved with.

**Comment by 54k1** [comment]
> - trait support
> - modules support
> - multifile support (in pair with modules)
> - type casting (with as)

That would be very cool!

> I am a bit sceptical static analysis will help to speed up the runtime significantly. I am glad to be mistaken tho.

Yes, I think you are right. It would not be anything major. A major speedup boost can be obtained by interpreting bytecode rather than syntax trees (since you would not be jumping around the heap as much).
Static analysis could result in some speedup, however, a greater benefit lies in having the errors reported to the programmer at compile time.

> If you are interested in the development of the static analysis tool, you have the green light for sure, either you choose to integrate it directly within this project (through a separate crate) or first develop as a standalone tool in its own repository to experiment with.
This is a great opportunity to dive into such a thing and I am sure it is an interesting initiative. Let me know what you decide to get involved with.

Sure. I'll keep you posted regarding this.
